### ISSUE TITLE
PostgreSQL 16, 15 and 14 support

### ISSUE THREAD

**Issue by devrimgunduz** [pierreforstmann/pg_readonly#8] opened 2023-09-11 11:02 UTC
Hi,

pg_readonly does not build against recent PostgreSQL versions. Will you add support for them?

Thanks!

Regards, Devrim

**Comment by pierreforstmann** [comment] 2023-09-11 16:41
Hi,

Yes I will support them.

I have made some tests with latest PG  versions using pgenv on Alma Linux 8.8 and found no build or regression issues.

I am using :
`This is 'pgenv' version 1.3.2 [7214768]`

NB: I had anaconda-core installed and I have removed it to fix:
```
make
x86_64-conda-linux-gnu-cc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/pierre/anaconda3/include -fdebug-prefix-map=/opt/conda/conda-bld/postgresql-split_1656062814261/work=/usr/local/src/conda/postgresql-split-12.9 -fdebug-prefix-map=/home/pierre/anaconda3=/usr/local/src/conda-prefix -fPIC -I. -I./ -I/home/pierre/anaconda3/include/server -I/home/pierre/anaconda3/include/internal  -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/pierre/anaconda3/include -D_GNU_SOURCE  -I/home/pierre/anaconda3/include  -c -o pg_readonly.o pg_readonly.c
make: x86_64-conda-linux-gnu-cc: Command not found
make: *** [<builtin>: pg_readonly.o] Error 127
```
Here are my build outputs:

For 16rc1:
```

(base) [pierre@alma pg_readonly]$ pgenv use 16rc1
[DEBUG] pg_ctl stopping with flags []
PostgreSQL 15.4 stopped
[DEBUG] initdb running with flags [-U postgres --locale en_US.UTF-8 --encoding UNICODE]
The files belonging to this database system will be owned by user "pierre".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /home/pierre/.pgenv/pgsql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Europe/Paris
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /home/pierre/.pgenv/pgsql/bin/pg_ctl -D /home/pierre/.pgenv/pgsql/data -l logfile start

[DEBUG] Directory /home/pierre/.pgenv/pgsql/data exists, not initdb-ing!
[DEBUG] pg_ctl starting instance with flags [] log [/home/pierre/.pgenv/pgsql/data/server.log]
PostgreSQL 16rc1 started
Logging to /home/pierre/.pgenv/pgsql/data/server.log
(base) [pierre@alma pg_readonly]$ make clean
rm -f pg_readonly.so pg_readonly.o  \
    pg_readonly.bc
rm -rf results/ regression.diffs regression.out tmp_check/ tmp_check_iso/ log/ output_iso/
(base) [pierre@alma pg_readonly]$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -fPIC -fvisibility=hidden -I. -I./ -I/home/pierre/.pgenv/pgsql-16rc1/include/server -I/home/pierre/.pgenv/pgsql-16rc1/include/internal  -D_GNU_SOURCE   -c -o pg_readonly.o pg_readonly.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -fPIC -fvisibility=hidden pg_readonly.o -L/home/pierre/.pgenv/pgsql-16rc1/lib   -Wl,--as-needed -Wl,-rpath,'/home/pierre/.pgenv/pgsql-16rc1/lib',--enable-new-dtags  -fvisibility=hidden -shared -o pg_readonly.so
(base) [pierre@alma pg_readonly]$ make install
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-16rc1/share/extension'
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-16rc1/share/extension'
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-16rc1/lib'
/usr/bin/install -c -m 644 .//pg_readonly.control '/home/pierre/.pgenv/pgsql-16rc1/share/extension/'
/usr/bin/install -c -m 644 .//pg_readonly--1.0.0.sql  '/home/pierre/.pgenv/pgsql-16rc1/share/extension/'
/usr/bin/install -c -m 755  pg_readonly.so '/home/pierre/.pgenv/pgsql-16rc1/lib/'
(base) [pierre@alma pg_readonly]$ make installcheck
echo "# +++ regress install-check in  +++" && /home/pierre/.pgenv/pgsql-16rc1/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/home/pierre/.pgenv/pgsql-16rc1/bin'    --temp-instance=/tmp/5555 --port=5555 --temp-config pg_readonly.conf --dbname=contrib_regression test 
# +++ regress install-check in  +++
# using temp instance on port 5555 with PID 27657
ok 1         - test                                        8 ms
1..1
```

For 15.4:

```
(base) [pierre@alma pg_readonly]$ pgenv use 15.4
[DEBUG] pg_ctl stopping with flags []
PostgreSQL 14.9 stopped
[DEBUG] Directory /home/pierre/.pgenv/pgsql/data exists, not initdb-ing!
[DEBUG] Directory /home/pierre/.pgenv/pgsql/data exists, not initdb-ing!
[DEBUG] pg_ctl starting instance with flags [] log [/home/pierre/.pgenv/pgsql/data/server.log]
PostgreSQL 15.4 started
Logging to /home/pierre/.pgenv/pgsql/data/server.log
(base) [pierre@alma pg_readonly]$ make clean
rm -f pg_readonly.so pg_readonly.o  \
    pg_readonly.bc
rm -rf results/ regression.diffs regression.out tmp_check/ tmp_check_iso/ log/ output_iso/
(base) [pierre@alma pg_readonly]$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -fPIC -I. -I./ -I/home/pierre/.pgenv/pgsql-15.4/include/server -I/home/pierre/.pgenv/pgsql-15.4/include/internal  -D_GNU_SOURCE   -c -o pg_readonly.o pg_readonly.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -fPIC pg_readonly.o -L/home/pierre/.pgenv/pgsql-15.4/lib   -Wl,--as-needed -Wl,-rpath,'/home/pierre/.pgenv/pgsql-15.4/lib',--enable-new-dtags  -shared -o pg_readonly.so
(base) [pierre@alma pg_readonly]$ make install
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-15.4/share/extension'
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-15.4/share/extension'
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-15.4/lib'
/usr/bin/install -c -m 644 .//pg_readonly.control '/home/pierre/.pgenv/pgsql-15.4/share/extension/'
/usr/bin/install -c -m 644 .//pg_readonly--1.0.0.sql  '/home/pierre/.pgenv/pgsql-15.4/share/extension/'
/usr/bin/install -c -m 755  pg_readonly.so '/home/pierre/.pgenv/pgsql-15.4/lib/'
(base) [pierre@alma pg_readonly]$ make installcheck
echo "+++ regress install-check in  +++" && /home/pierre/.pgenv/pgsql-15.4/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/home/pierre/.pgenv/pgsql-15.4/bin'    --temp-instance=/tmp/5555 --port=5555 --temp-config pg_readonly.conf --dbname=contrib_regression test 
+++ regress install-check in  +++
============== creating temporary instance            ==============
============== initializing database system           ==============
============== starting postmaster                    ==============
running on port 5555 with PID 24697
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
ALTER DATABASE
ALTER DATABASE
ALTER DATABASE
ALTER DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test test                         ... ok            8 ms
============== shutting down postmaster               ==============
============== removing temporary instance            ==============

=====================
 All 1 tests passed. 
=====================

```

For 14.9:
```
(base) [pierre@alma ~]$ pgenv use 14.9
PostgreSQL 15.4 not running
[DEBUG] initdb running with flags [-U postgres --locale en_US.UTF-8 --encoding UNICODE]
The files belonging to this database system will be owned by user "pierre".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /home/pierre/.pgenv/pgsql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Europe/Paris
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /home/pierre/.pgenv/pgsql/bin/pg_ctl -D /home/pierre/.pgenv/pgsql/data -l logfile start

[DEBUG] Directory /home/pierre/.pgenv/pgsql/data exists, not initdb-ing!
[DEBUG] pg_ctl starting instance with flags [] log [/home/pierre/.pgenv/pgsql/data/server.log]
PostgreSQL 14.9 started
Logging to /home/pierre/.pgenv/pgsql/data/server.log
(base) [pierre@alma ~]$ cd pg_readonly/
(base) [pierre@alma pg_readonly]$ git pull
Already up to date.
(base) [pierre@alma pg_readonly]$ make clean
rm -f pg_readonly.so pg_readonly.o  \
    pg_readonly.bc
rm -rf results/ regression.diffs regression.out tmp_check/ tmp_check_iso/ log/ output_iso/
(base) [pierre@alma pg_readonly]$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -fPIC -I. -I./ -I/home/pierre/.pgenv/pgsql-14.9/include/server -I/home/pierre/.pgenv/pgsql-14.9/include/internal  -D_GNU_SOURCE   -c -o pg_readonly.o pg_readonly.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -fPIC pg_readonly.o -L/home/pierre/.pgenv/pgsql-14.9/lib   -Wl,--as-needed -Wl,-rpath,'/home/pierre/.pgenv/pgsql-14.9/lib',--enable-new-dtags  -shared -o pg_readonly.so
(base) [pierre@alma pg_readonly]$ make install
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-14.9/share/extension'
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-14.9/share/extension'
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-14.9/lib'
/usr/bin/install -c -m 644 .//pg_readonly.control '/home/pierre/.pgenv/pgsql-14.9/share/extension/'
/usr/bin/install -c -m 644 .//pg_readonly--1.0.0.sql  '/home/pierre/.pgenv/pgsql-14.9/share/extension/'
/usr/bin/install -c -m 755  pg_readonly.so '/home/pierre/.pgenv/pgsql-14.9/lib/'
(base) [pierre@alma pg_readonly]$ make installcheck
/home/pierre/.pgenv/pgsql-14.9/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/home/pierre/.pgenv/pgsql-14.9/bin'    --temp-instance=/tmp/5555 --port=5555 --temp-config pg_readonly.conf --dbname=contrib_regression test 
============== creating temporary instance            ==============
============== initializing database system           ==============
============== starting postmaster                    ==============
running on port 5555 with PID 21653
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test test                         ... ok            6 ms
============== shutting down postmaster               ==============
============== removing temporary instance            ==============

=====================
 All 1 tests passed. 
=====================
```

Could you share details about used platform, building tools and build errors ?

**Comment by devrimgunduz** [comment] 2023-09-11 21:57
Hi @pierreforstmann ,

Thanks for the quick response. Right, it builds on all major platforms. Mine is Fedora 38 and GCC 13.2, and I believe that is the actual issue (as I also tried on RHEL 9). So it is just blocking Fedora at this point. See below for the error messages.

Regards, Devrim

> /usr/lib64/ccache/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Xclang -no-opaque-pointers -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -O2  -I. -I./ -I/usr/pgsql-16/include/server -I/usr/pgsql-16/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include -flto=thin -emit-llvm -c -o pg_readonly.bc pg_readonly.c
pg_readonly.c: In function '_PG_init':
pg_readonly.c:318:33: warning: assignment to 'post_parse_analyze_hook_type' {aka 'void (*)(ParseState *, Query *, JumbleState *)'} from incompatible pointer type 'void (*)(ParseState *, Query *)' [-Wincompatible-pointer-types]
  318 |         post_parse_analyze_hook = pgro_main;
      |                                 ^
pg_readonly.c: In function 'pgro_main':
pg_readonly.c:459:18: error: too few arguments to function 'prev_post_parse_analyze_hook'
  459 |                 (*prev_post_parse_analyze_hook)(pstate, query);
      |                 ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[1]: *** [<builtin>: pg_readonly.o] Error 1
make[1]: *** Waiting for unfinished jobs....
pg_readonly.c:318:26: error: incompatible function pointer types assigning to 'post_parse_analyze_hook_type' (aka 'void (*)(struct ParseState *, struct Query *, struct JumbleState *)') from 'void (ParseState *, Query *)' (aka 'void (struct ParseState *, struct Query *)') [-Wincompatible-function-pointer-types]
        post_parse_analyze_hook = pgro_main;
                                ^ ~~~~~~~~~
pg_readonly.c:459:48: error: too few arguments to function call, expected 3, have 2
                (*prev_post_parse_analyze_hook)(pstate, query); 
                ~~~~~~~~~~~

**Comment by pierreforstmann** [comment] 2023-09-12 18:34
Hi,

I cannot reproduce with following setup on Fedora 38:

```
[pierre@fedo38 pg_readonly]$ cat /etc/fedora-release 
Fedora release 38 (Thirty Eight)
[pierre@fedo38 pg_readonly]$ uname -a
Linux fedo38 6.2.9-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 22:32:58 UTC 2023 x86_64 GNU/Linux
[pierre@fedo38 pg_readonly]$ gcc --version
gcc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[pierre@fedo38 pg_readonly]$ pgenv --version
Unknown command `--version`
Usage: pgenv <command> [<args>]

The pgenv commands are:
    use        Set and start the current PostgreSQL version
    start      Start the current PostgreSQL server
    stop       Stop the current PostgreSQL server
    restart    Restart the current PostgreSQL server
    switch     Set the current PostgreSQL version
    clear      Stop and unset the current PostgreSQL version
    build      Build a specific version of PostgreSQL
    rebuild    Re-build a specific version of PostgreSQL
    remove     Remove a specific version of PostgreSQL
    version    Show the current PostgreSQL version
    current    Same as 'version'
    versions   List all PostgreSQL versions available to pgenv
    help       Show this usage statement and command summary
    available  Show which versions can be downloaded
    check      Check all program dependencies
    config     View, edit, delete the program configuration
    log        Inspects the log of the cluster, if exist.

For full documentation, see: https://github.com/theory/pgenv#readme

This is 'pgenv' version 1.3.2 [7214768]

```

I can build without any error or warning pg_readonly with PG 14.9, 15.4 and 16rc1.
Here is the output with PG 16rc1:

```
[pierre@fedo38 pg_readonly]$ make clean
rm -f pg_readonly.so pg_readonly.o  \
    pg_readonly.bc
rm -rf results/ regression.diffs regression.out tmp_check/ tmp_check_iso/ log/ output_iso/
[pierre@fedo38 pg_readonly]$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -fvisibility=hidden -I. -I./ -I/home/pierre/.pgenv/pgsql-16rc1/include/server -I/home/pierre/.pgenv/pgsql-16rc1/include/internal  -D_GNU_SOURCE   -c -o pg_readonly.o pg_readonly.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -fvisibility=hidden pg_readonly.o -L/home/pierre/.pgenv/pgsql-16rc1/lib   -Wl,--as-needed -Wl,-rpath,'/home/pierre/.pgenv/pgsql-16rc1/lib',--enable-new-dtags -fvisibility=hidden -shared -o pg_readonly.so
[pierre@fedo38 pg_readonly]$ make install
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-16rc1/share/extension'
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-16rc1/share/extension'
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-16rc1/lib'
/usr/bin/install -c -m 644 .//pg_readonly.control '/home/pierre/.pgenv/pgsql-16rc1/share/extension/'
/usr/bin/install -c -m 644 .//pg_readonly--1.0.0.sql  '/home/pierre/.pgenv/pgsql-16rc1/share/extension/'
/usr/bin/install -c -m 755  pg_readonly.so '/home/pierre/.pgenv/pgsql-16rc1/lib/'
[pierre@fedo38 pg_readonly]$ make installcheck
echo "# +++ regress install-check in  +++" && /home/pierre/.pgenv/pgsql-16rc1/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/home/pierre/.pgenv/pgsql-16rc1/bin'    --temp-instance=/tmp/5555 --port=5555 --temp-config pg_readonly.conf --dbname=contrib_regression test 
# +++ regress install-check in  +++
# using temp instance on port 5555 with PID 40746
ok 1         - test                                        7 ms
1..1
# All 1 tests passed.

```

**Comment by pierreforstmann** [comment] 2023-09-12 18:50
Error could be triggered by having a wrong value for macro for PG_VERSION_NUM or maybe an old pg_readonly version.

Could you please check that you are building pg_readonly 1.0.3 from `https://api.pgxn.org/dist/pg_readonly/1.0.3/pg_readonly-1.0.3.zip` ?

Thanks.

**Comment by pierreforstmann** [comment] 2023-09-19 16:37
Hi,

I have compiled PG 16.0 and pg_readonly 1.0.3 on fedora 38 without any issue:

```

[pierre@fedo38 ~]$ uname -a
Linux fedo38 6.2.9-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 22:32:58 UTC 2023 x86_64 GNU/Linux
[pierre@fedo38 ~]$ cat /etc/fedora-release 
Fedora release 38 (Thirty Eight)
[pierre@fedo38 ~]$ gcc --version
gcc (GCC) 13.2.1 20230728 (Red Hat 13.2.1-1)
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[pierre@fedo38 ~]$ 

[pierre@fedo38 ~]$ wget https://api.pgxn.org/dist/pg_readonly/1.0.3/pg_readonly-1.0.3.zip
--2023-09-19 18:31:33--  https://api.pgxn.org/dist/pg_readonly/1.0.3/pg_readonly-1.0.3.zip
Resolving api.pgxn.org (api.pgxn.org)... 88.198.49.178
Connecting to api.pgxn.org (api.pgxn.org)|88.198.49.178|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8787 (8.6K) [application/zip]
Saving to: ‘pg_readonly-1.0.3.zip’

pg_readonly-1.0.3.zip                     100%[==================================================================================>]   8.58K  --.-KB/s    in 0s      

2023-09-19 18:31:33 (218 MB/s) - ‘pg_readonly-1.0.3.zip’ saved [8787/8787]

[pierre@fedo38 ~]$ unzip pg_readonly-1.0.3.zip
Archive:  pg_readonly-1.0.3.zip
62fecd06677d39963162b8e800a07306d9d9be03
  inflating: pg_readonly-1.0.3/META.json  
  inflating: pg_readonly-1.0.3/Makefile  
  inflating: pg_readonly-1.0.3/README.md  
   creating: pg_readonly-1.0.3/expected/
  inflating: pg_readonly-1.0.3/expected/test.out  
  inflating: pg_readonly-1.0.3/pg_readonly--1.0.0.sql  
  inflating: pg_readonly-1.0.3/pg_readonly.c  
  inflating: pg_readonly-1.0.3/pg_readonly.conf  
  inflating: pg_readonly-1.0.3/pg_readonly.control  
   creating: pg_readonly-1.0.3/sql/
  inflating: pg_readonly-1.0.3/sql/test.sql  
[pierre@fedo38 ~]$ cd pg_readonly-1.0.3/
pierre@fedo38 pg_readonly-1.0.3]$ pgenv use 16.0
The files belonging to this database system will be owned by user "pierre".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

creating directory /home/pierre/.pgenv/pgsql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Europe/Paris
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok

initdb: warning: enabling "trust" authentication for local connections
initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    /home/pierre/.pgenv/pgsql/bin/pg_ctl -D /home/pierre/.pgenv/pgsql/data -l logfile start

PostgreSQL 16.0 started
Logging to /home/pierre/.pgenv/pgsql/data/server.log
[pierre@fedo38 pg_readonly-1.0.3]$ make clean
rm -f pg_readonly.so pg_readonly.o  \
    pg_readonly.bc
rm -rf results/ regression.diffs regression.out tmp_check/ tmp_check_iso/ log/ output_iso/
[pierre@fedo38 pg_readonly-1.0.3]$ make
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -fvisibility=hidden -I. -I./ -I/home/pierre/.pgenv/pgsql-16.0/include/server -I/home/pierre/.pgenv/pgsql-16.0/include/internal  -D_GNU_SOURCE   -c -o pg_readonly.o pg_readonly.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -fvisibility=hidden pg_readonly.o -L/home/pierre/.pgenv/pgsql-16.0/lib   -Wl,--as-needed -Wl,-rpath,'/home/pierre/.pgenv/pgsql-16.0/lib',--enable-new-dtags -fvisibility=hidden -shared -o pg_readonly.so
[pierre@fedo38 pg_readonly-1.0.3]$ make install
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-16.0/share/extension'
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-16.0/share/extension'
/usr/bin/mkdir -p '/home/pierre/.pgenv/pgsql-16.0/lib'
/usr/bin/install -c -m 644 .//pg_readonly.control '/home/pierre/.pgenv/pgsql-16.0/share/extension/'
/usr/bin/install -c -m 644 .//pg_readonly--1.0.0.sql  '/home/pierre/.pgenv/pgsql-16.0/share/extension/'
/usr/bin/install -c -m 755  pg_readonly.so '/home/pierre/.pgenv/pgsql-16.0/lib/'
[pierre@fedo38 pg_readonly-1.0.3]$ make installcheck
echo "# +++ regress install-check in  +++" && /home/pierre/.pgenv/pgsql-16.0/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/home/pierre/.pgenv/pgsql-16.0/bin'    --temp-instance=/tmp/5555 --port=5555 --temp-config pg_readonly.conf --dbname=contrib_regression test 
# +++ regress install-check in  +++
# using temp instance on port 5555 with PID 10929
ok 1         - test                                        7 ms
1..1
# All 1 tests passed.
[pierre@fedo38 pg_readonly-1.0.3]$ 

```

**Comment by pierreforstmann** [comment] 2023-09-19 16:38
I'm closing this issue as I cannot reproduce with latest PG version and latest pg_readonly version on Fedora 38.

**Closed as completed by pierreforstmann** 2023-09-19 16:37 UTC
